# Generated by Django 3.1.9 on 2021-10-05 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filer', '0013_image_width_height_to_float'),
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageGallery',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='corebytecms_gallery_imagegallery', serialize=False, to='cms.cmsplugin')),
                ('name', models.CharField(max_length=255, verbose_name='Gallery name')),
                ('folder', models.ForeignKey(help_text='Select folder with gallery images.', on_delete=django.db.models.deletion.CASCADE, related_name='gallery_folder', to='filer.folder', verbose_name='Folder')),
            ],
            options={
                'verbose_name': 'Image gallery',
                'verbose_name_plural': 'Image galleries',
                'ordering': ['pk'],
            },
            bases=('cms.cmsplugin',),
        ),
    ]
